
install.packages("anytime")
install.packages("cmocean")
install.packages("ggplot2")
install.packages("rworldxtra")
install.packages("rworldmap")

#library(animation)
#library(abind)
#library(doParallel)
#library(gridExtra)
#library(imputeTS)
#library(latex2exp)
#library(mgcv)
#library(modelr)
#library(mgcViz)
#library(parallel)
#library(reshape2)
#library(rgeos)
#library(rgdal)
#library(spatialEco)
#library(stlplus)
#library(sp)
#library(sf)
#library(tidyverse)
#library(viridis)
#library(zoo)

